# Generated by Django 5.2.7 on 2026-01-21 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_reset_completed_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
