# Generated by Django 5.2.7 on 2025-12-24 01:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Franchises',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('igdb_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('game_title', models.CharField(max_length=255, unique=True)),
                ('cover_artwork_link', models.TextField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('completion_time', models.IntegerField(blank=True, null=True)),
                ('completionist_completion_time', models.IntegerField(blank=True, null=True)),
                ('average_rating', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Platforms',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publishers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameSpecificDevelopers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('developer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.developers')),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.games')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('game_id', 'developer_id'), name='Developers for a Specific Game')],
            },
        ),
        migrations.CreateModel(
            name='GameSpecificFranchises',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('franchise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.franchises')),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.games')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('game_id', 'franchise_id'), name='Franchises for a Specific Game')],
            },
        ),
        migrations.CreateModel(
            name='GameSpecificGenres',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.games')),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.genres')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('game_id', 'genre_id'), name='Genres for a Specific Game')],
            },
        ),
        migrations.CreateModel(
            name='GameSpecificPlatforms',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.games')),
                ('platform_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.platforms')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('game_id', 'platform_id'), name='Platforms for a Specific Game')],
            },
        ),
        migrations.CreateModel(
            name='GameSpecificPublishers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.games')),
                ('publisher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.publishers')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('game_id', 'publisher_id'), name='Publishers for a Specific Game')],
            },
        ),
        migrations.CreateModel(
            name='GameSpecificSeries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.games')),
                ('series_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.series')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('game_id', 'series_id'), name='Series for a Specific Game')],
            },
        ),
    ]
