# Generated by Django 5.2.7 on 2026-01-03 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='game_title',
            field=models.CharField(max_length=255),
        ),
    ]
