# Generated by Django 5.2.7 on 2026-01-14 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_games_game_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
