# Generated by Django 5.2.7 on 2025-12-24 01:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logs', '0001_initial'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlists',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('playlist_title', models.CharField(max_length=32)),
                ('creation_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profiles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistLogs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_position', models.IntegerField(blank=True, null=True)),
                ('log_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs.logs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('playlist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlists.playlists')),
            ],
        ),
        migrations.AddConstraint(
            model_name='playlists',
            constraint=models.UniqueConstraint(fields=('profile_id', 'playlist_title'), name='user_playlists'),
        ),
        migrations.AddConstraint(
            model_name='playlistlogs',
            constraint=models.UniqueConstraint(fields=('playlist_id', 'log_id'), name='user_playlist_entry_logs'),
        ),
    ]
