# Generated by Django 5.2.7 on 2025-12-24 01:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recommendation_match', models.DecimalField(decimal_places=2, max_digits=4)),
                ('creation_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.games')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profiles')),
            ],
        ),
    ]
