# Generated by Django 5.2.7 on 2025-12-24 01:16

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_status', models.CharField(choices=[('backlog', 'Backlog'), ('playing', 'Playing'), ('paused', 'Paused'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='backlog', max_length=12)),
                ('user_rating', models.IntegerField(blank=True, null=True)),
                ('user_review', models.TextField(blank=True, max_length=255, null=True)),
                ('user_playtime', models.IntegerField(blank=True, default=0, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('full_completion', models.BooleanField(default=False)),
                ('creation_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.games')),
                ('platform_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.platforms')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profiles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogSessions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_playtime', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(blank=True, default=datetime.datetime(2025, 12, 24, 1, 16, 19, 4161, tzinfo=datetime.timezone.utc), null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('creation_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('log_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs.logs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogTags',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('log_tag', models.CharField(max_length=32)),
                ('log_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs.logs')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profiles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='logs',
            constraint=models.UniqueConstraint(fields=('profile_id', 'game_id', 'platform_id'), name='user_entry_logs'),
        ),
        migrations.AddConstraint(
            model_name='logtags',
            constraint=models.UniqueConstraint(fields=('log_id', 'log_tag'), name='log_entry_tags'),
        ),
    ]
