# Generated by Django 5.2.7 on 2025-12-31 23:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsessions',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 12, 31, 23, 9, 16, 313959, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
