# Generated by Django 5.2.7 on 2026-01-04 00:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_alter_logsessions_start_time'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='profile_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.profiles'),
        ),
        migrations.AlterField(
            model_name='logsessions',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 1, 4, 0, 56, 48, 373196, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
