# Generated by Django 5.2.7 on 2026-01-04 02:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_games_game_title'),
        ('logs', '0004_alter_logs_profile_id_alter_logsessions_start_time'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='full_completion',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='logs',
            name='platform_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.platforms'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profiles'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='user_status',
            field=models.CharField(blank=True, choices=[('backlog', 'Backlog'), ('playing', 'Playing'), ('paused', 'Paused'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='backlog', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='logsessions',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 1, 4, 2, 7, 9, 316343, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
