# Generated by Django 5.2.7 on 2026-01-04 02:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_alter_logs_full_completion_alter_logs_platform_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsessions',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 1, 4, 2, 22, 52, 949620, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
