# Generated by Django 5.2.7 on 2026-01-08 20:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0007_alter_logsessions_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsessions',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 1, 8, 20, 22, 43, 121644, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
