# Generated by Django 5.2.7 on 2026-01-12 00:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0011_alter_logsessions_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsessions',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 1, 12, 0, 6, 32, 540961, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
