# Generated by Django 5.2.7 on 2026-01-15 22:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0016_alter_logsessions_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsessions',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 1, 15, 22, 48, 42, 306723, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
