# Generated by Django 5.2.7 on 2026-01-21 01:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0024_alter_logsessions_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsessions',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 1, 21, 1, 45, 32, 203435, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
