# Generated by Django 5.2.7 on 2025-12-24 01:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKeys',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('api_token_prefix', models.CharField(max_length=8, unique=True)),
                ('creation_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_fetched', models.DateTimeField(blank=True, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('expired', models.BooleanField(default=False)),
                ('rotate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.apikeys')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, max_length=32, null=True)),
                ('profile_picture', models.ImageField(default='profile_pictures/default.jpg', upload_to='profile_pictures')),
                ('private_profile', models.BooleanField(default=False)),
                ('website_theme', models.CharField(choices=[('dark', 'Dark'), ('light', 'Light'), ('orange', 'Orange'), ('lemon', 'Lemon'), ('strawberry', 'Strawberry'), ('blueberry', 'Blueberry')], default='dark', max_length=20)),
                ('bio', models.TextField(blank=True, max_length=255, null=True)),
                ('playstyle', models.CharField(blank=True, choices=[('casual', 'Casual'), ('completionist', 'Completionist'), ('story_focused', 'Story Focused'), ('gameplay_focused', 'Gameplay Focused'), ('indie_gamer', 'Indie Gamer'), ('heavy_gamer', 'Heavy Gamer'), ('competitive_gamer', 'Competitive Gamer'), ('single_player', 'Single-Player'), ('multi_player', 'Multi-Player')], default='casual', max_length=32, null=True)),
                ('favorite_developer', models.ManyToManyField(blank=True, to='games.developers')),
                ('favorite_franchise', models.ManyToManyField(blank=True, to='games.franchises')),
                ('favorite_game', models.ManyToManyField(blank=True, to='games.games')),
                ('favorite_genre', models.ManyToManyField(blank=True, to='games.genres')),
                ('favorite_platform', models.ManyToManyField(blank=True, to='games.platforms')),
                ('favorite_publisher', models.ManyToManyField(blank=True, to='games.publishers')),
                ('favorite_series', models.ManyToManyField(blank=True, to='games.series')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
