# Generated by Django 5.2.7 on 2026-01-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profiles_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='profiles',
            name='profile_photo',
            field=models.ImageField(default='profile_pictures/default.jpg', upload_to='profile_pictures'),
        ),
    ]
