# Generated by Django 5.2.7 on 2026-01-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_profiles_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=255, null=True),
        ),
    ]
