# Generated by Django 5.2.7 on 2026-01-15 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_games_summary'),
        ('profiles', '0004_alter_profiles_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='favorite_game',
        ),
        migrations.AddField(
            model_name='profiles',
            name='favorite_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.games'),
        ),
    ]
