# Generated by Django 5.2.7 on 2026-01-21 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_profiles_favorite_game_profiles_favorite_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='display_name',
        ),
    ]
