# Generated by Django 5.2.7 on 2025-12-23 03:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SteamProfiles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('steam_id', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('steam_username', models.CharField(blank=True, max_length=32, null=True)),
                ('steam_avatar_link', models.TextField(blank=True, null=True)),
                ('steam_public_profile', models.BooleanField(blank=True, default=True, null=True)),
                ('auto_sync_playtime', models.BooleanField(blank=True, default=False, null=True)),
                ('auto_sync_games', models.BooleanField(blank=True, default=False, null=True)),
                ('creation_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_fetched', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
